#ifndef ETH_DAT_GEN_H
#define ETH_DAT_GEN_H

#define DAT_FIFO_BASE_ADDR  0x43C10000
#define DAT_FIFO_ISR_OFFSET 0x0
#define DAT_FIFO_WP_OFFSET  0x10
#define DAT_FIFO_TLR_OFFSET 0x14

void WRITE_DAT_FIFO();

#endif // ETH_DAT_GEN_H